steps:
  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "functions"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--runtime"
      - "nodejs20"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--region"
      - "us-east1"
      - "--entry-point"
      - "api"
      - "--project"
      - "$PROJECT_ID"
    waitFor: ["-"]

  # Build and Deploy Next.js App
  - name: "node:20"
    id: "npm-install"
    entrypoint: "npm"
    args: ["install"]
    waitFor: ["-"]

  - name: "node:20"
    id: "build-next-app"
    entrypoint: "npm"
    args: ["run", "build"]
    availableSecrets:
      secretManager:
        - versionName: "projects/veredicto-v2/secrets/GEMINI_API_KEY/versions/1"
          env: "GEMINI_API_KEY"
        - versionName: "projects/veredicto-v2/secrets/NEXT_PUBLIC_BASE_URL/versions/1"
          env: "NEXT_PUBLIC_BASE_URL"
        - versionName: "projects/veredicto-v2/secrets/MONGO_URI/versions/1"
          env: "MONGO_URI"
        - versionName: "projects/veredicto-v2/secrets/STRIPE_SECRET/versions/1"
          env: "STRIPE_SECRET"
        - versionName: "projects/veredicto-v2/secrets/STRIPE_WH_SECRET/versions/1"
          env: "STRIPE_WH_SECRET"
        - versionName: "projects/veredicto-v2/secrets/NEXT_PUBLIC_STRIPE_PK/versions/1"
          env: "NEXT_PUBLIC_STRIPE_PK"
        - versionName: "projects/veredicto-v2/secrets/BREVO_API_KEY/versions/1"
          env: "BREVO_API_KEY"
        - versionName: "projects/veredicto-v2/secrets/BETTER_AUTH_SECRET/versions/1"
          env: "BETTER_AUTH_SECRET"
        - versionName: "projects/veredicto-v2/secrets/BETTER_AUTH_URL/versions/1"
          env: "BETTER_AUTH_URL"

    waitFor:
      - "npm-install"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-next-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "veredicto-v2"
      - "--source"
      - "."
      - "--region"
      - "us-east1"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
    waitFor:
      - "build-next-app"

options:
  logging: CLOUD_LOGGING_ONLY
