steps:
  # Build and push Next.js container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "build-next"
    entrypoint: "bash"
    args:
      - -ceu
      - |
        docker build \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA \
          --build-arg NEXT_PUBLIC_BASE_URL="$NEXT_PUBLIC_BASE_URL" \
          --build-arg NEXT_PUBLIC_STRIPE_PK="$NEXT_PUBLIC_STRIPE_PK" \
          --build-arg GEMINI_API_KEY="$GEMINI_API_KEY" \
          --build-arg MONGO_URI="$MONGO_URI" \
          --build-arg STRIPE_SECRET="$STRIPE_SECRET" \
          --build-arg STRIPE_WH_SECRET="$STRIPE_WH_SECRET" \
          --build-arg BREVO_API_KEY="$BREVO_API_KEY" \
          --build-arg BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET" \
          --build-arg BETTER_AUTH_URL="$BETTER_AUTH_URL" \
          .
    secretEnv: ['GEMINI_API_KEY','MONGO_URI','STRIPE_SECRET','STRIPE_WH_SECRET','BREVO_API_KEY','BETTER_AUTH_SECRET','BETTER_AUTH_URL','NEXT_PUBLIC_BASE_URL','NEXT_PUBLIC_STRIPE_PK']

  - name: "gcr.io/cloud-builders/docker"
    id: "push-next"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"

  # Deploy container to Cloud Run with runtime environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-next"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--memory"
      - "512Mi"
      - "--max-instances"
      - "3"
      - "--set-secrets"
      - >-
        NEXT_PUBLIC_BASE_URL=NEXT_PUBLIC_BASE_URL:latest,
        NEXT_PUBLIC_STRIPE_PK=NEXT_PUBLIC_STRIPE_PK:latest,
        GEMINI_API_KEY=GEMINI_API_KEY:latest,
        MONGO_URI=MONGO_URI:latest,
        STRIPE_SECRET=STRIPE_SECRET:latest,
        STRIPE_WH_SECRET=STRIPE_WH_SECRET:latest,
        BREVO_API_KEY=BREVO_API_KEY:latest,
        BETTER_AUTH_SECRET=BETTER_AUTH_SECRET:latest,
        BETTER_AUTH_URL=BETTER_AUTH_URL:latest

  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "functions"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--runtime"
      - "nodejs20"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--region"
      - "us-east1"
      - "--entry-point"
      - "app"
      - "--project"
      - "$PROJECT_ID"
    secretEnv: ['GEMINI_API_KEY', 'MONGO_URI']
    waitFor:
      - "-"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/537799247600/secrets/GEMINI_API_KEY/versions/latest"
      env: "GEMINI_API_KEY"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_BASE_URL"
    - versionName: "projects/537799247600/secrets/MONGO_URI/versions/latest"
      env: "MONGO_URI"
    - versionName: "projects/537799247600/secrets/STRIPE_SECRET/versions/latest"
      env: "STRIPE_SECRET"
    - versionName: "projects/537799247600/secrets/STRIPE_WH_SECRET/versions/latest"
      env: "STRIPE_WH_SECRET"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_STRIPE_PK/versions/latest"
      env: "NEXT_PUBLIC_STRIPE_PK"
    - versionName: "projects/537799247600/secrets/BREVO_API_KEY/versions/latest"
      env: "BREVO_API_KEY"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_SECRET/versions/latest"
      env: "BETTER_AUTH_SECRET"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_URL/versions/latest"
      env: "BETTER_AUTH_URL"

substitutions:
  _REGION: us-east1
  _REPO: web
  _SERVICE: veredicto-web