steps:
  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "functions"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--runtime"
      - "nodejs20"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--region"
      - "us-east1"
      - "--entry-point"
      - "app"
      - "--project"
      - "$PROJECT_ID"
    secretEnv: ['GEMINI_API_KEY', 'MONGO_URI']
    waitFor:
      - "-"

  # Build the Next.js container image, passing secrets
  - name: "gcr.io/cloud-builders/gcloud"
    id: "build-next-app-image"
    args:
      - "builds"
      - "submit"
      - "--tag"
      - "gcr.io/$PROJECT_ID/veredicto-v2:$COMMIT_SHA"
      - "."
    secretEnv: ["GEMINI_API_KEY",'NEXT_PUBLIC_BASE_URL', 'MONGO_URI', 'STRIPE_SECRET', 'STRIPE_WH_SECRET', 'NEXT_PUBLIC_STRIPE_PK', 'BREVO_API_KEY', 'BETTER_AUTH_SECRET', 'BETTER_AUTH_URL']
    waitFor:
      - "deploy-function"

  # Deploy the pre-built image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-next-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "veredicto-v2"
      - "--image"
      - "gcr.io/$PROJECT_ID/veredicto-v2:$COMMIT_SHA"
      - "--region"
      - "us-east1"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
    waitFor:
      - "build-next-app-image"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/537799247600/secrets/GEMINI_API_KEY/versions/latest"
      env: "GEMINI_API_KEY"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_BASE_URL"
    - versionName: "projects/537799247600/secrets/MONGO_URI/versions/latest"
      env: "MONGO_URI"
    - versionName: "projects/537799247600/secrets/STRIPE_SECRET/versions/latest"
      env: "STRIPE_SECRET"
    - versionName: "projects/537799247600/secrets/STRIPE_WH_SECRET/versions/latest"
      env: "STRIPE_WH_SECRET"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_STRIPE_PK/versions/latest"
      env: "NEXT_PUBLIC_STRIPE_PK"
    - versionName: "projects/537799247600/secrets/BREVO_API_KEY/versions/latest"
      env: "BREVO_API_KEY"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_SECRET/versions/latest"
      env: "BETTER_AUTH_SECRET"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_URL/versions/latest"
      env: "BETTER_AUTH_URL"