steps:
  # Install dependencies for the Next.js app using Node.js 20
  # - name: 'node:20'
  #   id: 'npm-install'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - 'npm ci'
  #   waitFor:
  #     - "-" # Assuming this is now the first step for the app

  # Build the Next.js app with secrets using Node.js 20
  # - name: 'node:20'
  #   id: 'npm-build'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - 'npm run build'
  #   secretEnv: ["GEMINI_API_KEY",'NEXT_PUBLIC_BASE_URL', 'MONGO_URI', 'STRIPE_SECRET', 'STRIPE_WH_SECRET', 'NEXT_PUBLIC_STRIPE_PK', 'BREVO_API_KEY', 'BETTER_AUTH_SECRET', 'BETTER_AUTH_URL']
  #   waitFor:
  #     - 'npm-install'

  # Build the Docker image using the pre-built artifacts
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    secretEnv: ["GEMINI_API_KEY",'NEXT_PUBLIC_BASE_URL', 'MONGO_URI', 'STRIPE_SECRET', 'STRIPE_WH_SECRET', 'NEXT_PUBLIC_STRIPE_PK', 'BREVO_API_KEY', 'BETTER_AUTH_SECRET', 'BETTER_AUTH_URL']
    args: [
      'build',
      '-e',
      'GEMINI_API_KEY=$GEMINI_API_KEY',
      '-e',
      'NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL',
      '-e',
      'MONGO_URI=$MONGO_URI',
      '-e',
      'STRIPE_SECRET=$STRIPE_SECRET',
      '-e',
      'STRIPE_WH_SECRET=$STRIPE_WH_SECRET',
      '-e',
      'NEXT_PUBLIC_STRIPE_PK=$NEXT_PUBLIC_STRIPE_PK',
      '-e',
      'BREVO_API_KEY=$BREVO_API_KEY',
      '-e',
      'BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET',
      '-e',
      'BETTER_AUTH_URL=$BETTER_AUTH_URL',
      '-t',
      'gcr.io/$PROJECT_ID/veredicto-v2:$COMMIT_SHA',
      '.'
    ]


  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: ['push', 'gcr.io/$PROJECT_ID/veredicto-v2:$COMMIT_SHA']
    waitFor:
      - 'docker-build'

  # Deploy the pre-built image to Cloud Run, attaching runtime secrets
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-next-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "veredicto-v2"
      - "--image"
      - "gcr.io/$PROJECT_ID/veredicto-v2:$COMMIT_SHA"
      - "--region"
      - "us-east1"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
      - "--set-secrets"
      - "GEMINI_API_KEY=GEMINI_API_KEY:latest,NEXT_PUBLIC_BASE_URL=NEXT_PUBLIC_BASE_URL:latest,MONGO_URI=MONGO_URI:latest,STRIPE_SECRET=STRIPE_SECRET:latest,STRIPE_WH_SECRET=STRIPE_WH_SECRET:latest,NEXT_PUBLIC_STRIPE_PK=NEXT_PUBLIC_STRIPE_PK:latest,BREVO_API_KEY=BREVO_API_KEY:latest,BETTER_AUTH_SECRET=BETTER_AUTH_SECRET:latest,BETTER_AUTH_URL=BETTER_AUTH_URL:latest"
    waitFor:
      - "docker-push"

  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "functions"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--runtime"
      - "nodejs20"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--region"
      - "us-east1"
      - "--entry-point"
      - "app"
      - "--project"
      - "$PROJECT_ID"
    secretEnv: ['GEMINI_API_KEY', 'MONGO_URI']
    waitFor:
      - "-"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/537799247600/secrets/GEMINI_API_KEY/versions/latest"
      env: "GEMINI_API_KEY"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_BASE_URL"
    - versionName: "projects/537799247600/secrets/MONGO_URI/versions/latest"
      env: "MONGO_URI"
    - versionName: "projects/537799247600/secrets/STRIPE_SECRET/versions/latest"
      env: "STRIPE_SECRET"
    - versionName: "projects/537799247600/secrets/STRIPE_WH_SECRET/versions/latest"
      env: "STRIPE_WH_SECRET"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_STRIPE_PK/versions/latest"
      env: "NEXT_PUBLIC_STRIPE_PK"
    - versionName: "projects/537799247600/secrets/BREVO_API_KEY/versions/latest"
      env: "BREVO_API_KEY"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_SECRET/versions/latest"
      env: "BETTER_AUTH_SECRET"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_URL/versions/latest"
      env: "BETTER_AUTH_URL"