steps:
  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "functions"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--runtime"
      - "nodejs20"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--region"
      - "us-east1"
      - "--entry-point"
      - "api"
      - "--project"
      - "$PROJECT_ID"
    secretEnv: ['GEMINI_API_KEY', 'MONGO_URI']
    waitFor: ["-"]

  # Build and Deploy Next.js App
  - name: "node:20"
    id: "npm-install"
    entrypoint: "npm"
    args: ["install"]
    waitFor: ["-"]

  - name: "node:20"
    id: "build-next-app"
    entrypoint: "npm"
    args: ["run", "build"]
    secretEnv: ['NEXT_PUBLIC_BASE_URL', 'MONGO_URI', 'STRIPE_SECRET', 'STRIPE_WH_SECRET', 'NEXT_PUBLIC_STRIPE_PK', 'BREVO_API_KEY', 'BETTER_AUTH_SECRET', 'BETTER_AUTH_URL']
    waitFor:
      - "npm-install"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-next-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "veredicto-v2"
      - "--source"
      - "."
      - "--region"
      - "us-east1"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
    waitFor:
      - "build-next-app"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/537799247600/secrets/GEMINI_API_KEY/versions/lastest"
      env: "GEMINI_API_KEY"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_BASE_URL/versions/lastest"
      env: "NEXT_PUBLIC_BASE_URL"
    - versionName: "projects/537799247600/secrets/MONGO_URI/versions/lastest"
      env: "MONGO_URI"
    - versionName: "projects/537799247600/secrets/STRIPE_SECRET/versions/lastest"
      env: "STRIPE_SECRET"
    - versionName: "projects/537799247600/secrets/STRIPE_WH_SECRET/versions/lastest"
      env: "STRIPE_WH_SECRET"
    - versionName: "projects/537799247600/secrets/NEXT_PUBLIC_STRIPE_PK/versions/lastest"
      env: "NEXT_PUBLIC_STRIPE_PK"
    - versionName: "projects/537799247600/secrets/BREVO_API_KEY/versions/lastest"
      env: "BREVO_API_KEY"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_SECRET/versions/lastest"
      env: "BETTER_AUTH_SECRET"
    - versionName: "projects/537799247600/secrets/BETTER_AUTH_URL/versions/lastest"
      env: "BETTER_AUTH_URL"