steps:
  # Deploy Cloud Function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-function"
    args:
      - "run"
      - "deploy"
      - "veredito-function"
      - "--source"
      - "./functions"
      - "--region"
      - "us-east1"
      - "--trigger-http"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
    waitFor: ["-"]

  # Build and Deploy Next.js App
  - name: "gcr.io/cloud-builders/npm"
    id: "npm-install"
    args: ["install"]
    waitFor: ["-"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "get-secrets"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=VEREDICTO_SECRETS --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env
    waitFor:
      - "npm-install"

  - name: "gcr.io/cloud-builders/npm"
    id: "build-next-app"
    args: ["run", "build"]
    waitFor:
      - "get-secrets"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-next-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "veredicto-v2"
      - "--source"
      - "."
      - "--region"
      - "us-east1"
      - "--allow-unauthenticated"
      - "--project"
      - "$PROJECT_ID"
    waitFor:
      - "build-next-app"

options:
  logging: CLOUD_LOGGING_ONLY
